name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version number
        id: get_version
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create source tarball
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          cd ..
          tar czf tuition-${VERSION}.tar.gz --transform "s,^cl-tuition,tuition-${VERSION}," \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='*.txt' \
            --exclude='*.lisp-temp' \
            --exclude='data/' \
            --exclude='.tools/' \
            cl-tuition
          mv tuition-${VERSION}.tar.gz cl-tuition/

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          bodyFile: docs/release-notes/RELEASE-NOTES-${{ steps.get_version.outputs.version }}.md
          artifacts: |
            tuition-${{ steps.get_version.outputs.version }}.tar.gz
          allowUpdates: true
